//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_log
    {
        public int id { get; set; }
        public string activitymessage { get; set; }
        public string activtystatus { get; set; }
        public string activityCode { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
