//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bundleProd
    {
        public int bundleID { get; set; }
        public string bundleCode { get; set; }
        public string bundleTitle { get; set; }
        public string bundleIntegratedProdFinal { get; set; }
        public string bundleIntegratedProdInvID { get; set; }
        public Nullable<int> bundleQuantity { get; set; }
        public Nullable<decimal> prodPrice { get; set; }
        public string prodImg { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string isvalidate { get; set; }
    }
}
