//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerBasicInformation
    {
        public int customerID { get; set; }
        public string customerName { get; set; }
        public string orderCodeIndicated { get; set; }
        public Nullable<decimal> orderPaymentIndicated { get; set; }
        public Nullable<decimal> orderTotalIndicated { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
