//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryReport
    {
        public int invID { get; set; }
        public string productName { get; set; }
        public Nullable<long> beg_qty { get; set; }
        public string available { get; set; }
        public Nullable<long> end_qty { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<int> refId { get; set; }
        public string refstatus { get; set; }
    }
}
