//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productreport
    {
        public int id { get; set; }
        public string problem1 { get; set; }
        public string problem2 { get; set; }
        public string problem3 { get; set; }
        public string problem4 { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string responsible { get; set; }
    }
}
