//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class puchase_orders
    {
        public int poid { get; set; }
        public string ponumber { get; set; }
        public string pname { get; set; }
        public Nullable<int> pquantity { get; set; }
        public Nullable<decimal> pprice { get; set; }
        public Nullable<decimal> ptotal { get; set; }
        public string pcreator { get; set; }
        public string psupplier { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
    }
}
