//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stocks_on_hand_dump
    {
        public int dumpId { get; set; }
        public string stockDumpName { get; set; }
        public Nullable<int> stockDumpId { get; set; }
        public Nullable<long> stockDumpNumber { get; set; }
        public Nullable<int> dumpQuantity { get; set; }
        public Nullable<System.DateTime> dumpExpiration { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<System.DateTime> dumpReceived { get; set; }
    }
}
