//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int id { get; set; }
        public string supplierIdentificationCode { get; set; }
        public string supplierfirstname { get; set; }
        public string supplierlastname { get; set; }
        public string supplierprimaryaddress { get; set; }
        public string suppliersecondaryaddress { get; set; }
        public string suppliernumber { get; set; }
        public string supplieremail { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string supplierimgurl { get; set; }
        public string isstatus { get; set; }
    }
}
