//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capstone_backend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbinventsetting
    {
        public int id { get; set; }
        public string enableinventform { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public string enablesupplier { get; set; }
        public string enableexpiration { get; set; }
    }
}
